### ISSUE TITLE
Question about processing a whole video

### ISSUE THREAD

**Issue by zhshi0816** [Mukosame/Zooming-Slow-Mo-CVPR-2020#16]
Hi,

I have a question about what should you do with a whole video. Let's say we have a whole video, (L1, L2, ...L14) and your processing window is 7.  What is your window stride now? What should you do now? Do you have overlapped problem? If so, how do you deal with it?

Many thanks

**Comment by Mukosame** [comment]
Hi,

Thanks for bringing this up. Please check this function: [test_index_generation](https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/codes/utils/util.py#L272)

The window size depends on you. For example, you have L1~L13 and window=7, then the first test sea would be: 1~7(1,3,5,7 -> 1234567), and then the second one would be 7~13(7,9,11,13->789 10 11 12 13). Only the "L7" is overlapped because it is necessary in generating both H6 and H8 in the two seqs.
Hope this can answer your question well :)
