### ISSUE TITLE
Shared cells for bidirectional lstm

### ISSUE THREAD

**Issue by NateLol** [Mukosame/Zooming-Slow-Mo-CVPR-2020#57]
Hi there,

I am curious about your choice of using the same cell for bidirectional lstm [here](https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/405c65b70e1df4268182d03f7bb539a3d9613e7b/codes/models/modules/Sakuya_arch.py#L253) as they are usually learned in a separate way.

Thanks,
Nate

**Comment by Mukosame** [comment]
Hi @NateLol , thanks for asking it! This loc is left because we actually tried using different cells before. There used to be a 'self.backward_net' in this line. It doesn't appear in the final version for two reasons:

1. less parameters;
2. no obvious performance improvement;
2.5 we use temporal augmentation (that is, randomly revert the sequence during the training). I guess that's part of the reason why reason 2 happens.

Please let me know if you have more questions :)

**Comment by NateLol** [comment]
Well explained thanks!!
